version: '3.8'

networks:
  net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 1.2.3.4/30
    driver_opts:
     com.docker.network.bridge.name: webmin_net
services:

  webmin:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROOT_PW: MYSAFEPASSWORD
    container_name: webmin
    restart: always
    ports:
      - 10000:10000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net
